apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mongo-express-deployment
  namespace: mongodb-app-ns
  labels:
    app:  mongo-express
spec:
  selector:
    matchLabels:
      app: mongo-express
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  mongo-express
    spec:
      containers:
        - name:  mongo-express-app
          image:  mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongo-db-config-map
                  key: database_url
            - name: ME_CONFIG_MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-db-config-map
                  key: database_url
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-db-secret
                  key: mongo-root-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-db-secret
                  key: mongo-root-password
            
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: mongodb-app-ns
spec:
  selector:
    app: mongo-express
  type: NodePort
  ports:
  - name: mongo-express-port
    protocol: TCP
    port: 8081 # this will be for the internal services. This is like its own private VPN
    targetPort: 8081 # this will be the container's port
