apiVersion: v1
kind: Secret
metadata:
  name: mongo-db-secret
  namespace: mongodb-app-ns
type: Opaque
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: cGFzc3dvcmQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-default-cluster-config
  namespace: argocd
type: Opaque
data:
  clusterResource: "dHJ1ZQo="
